# Generated by Django 4.1.5 on 2023-01-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricecard_id_alter_pricetable_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
